# Generated by Django 5.0.4 on 2024-04-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadedContents', '0002_uploadedcontent_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedcontent',
            name='uploadDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
