# Generated by Django 5.0.4 on 2024-04-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadedContents', '0003_alter_uploadedcontent_uploaddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedcontent',
            name='thumbnail',
            field=models.FileField(default=None, upload_to='Thumbnail/'),
        ),
        migrations.AlterField(
            model_name='uploadedcontent',
            name='videos',
            field=models.FileField(default=None, upload_to='Videos/'),
        ),
    ]
